### ISSUE TITLE
Python import error

### ISSUE THREAD

**Issue by Green-Sky** [flathub/studio.kx.carla#48]
decided to try the flatpak version, but it did not launch. Maybe I am missing a runtime, but then again it should install those.

```
$ flatpak run studio.kx.carla
Traceback (most recent call last):
  File "/app/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/app/share/carla/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/app/share/carla/ui_carla_host.py", line 847, in <module>
    from widgets.draggablegraphicsview import DraggableGraphicsView
  File "/app/share/carla/widgets/draggablegraphicsview.py", line 30, in <module>
    from carla_shared import MACOS, CustomMessageBox, gCarla
  File "/app/share/carla/carla_shared.py", line 41, in <module>
    from PyQt5.Qt import PYQT_VERSION_STR
ImportError: cannot import name 'PYQT_VERSION_STR' from 'PyQt5.Qt' (/app/lib/python3.10/site-packages/PyQt5/Qt.abi3.so)
```

**Comment by Bleuzen** [comment]
Please update in about 4 hours from now and try again

**Comment by Bleuzen** [comment]
@Green-Sky build is live, you can test now

**Comment by Green-Sky** [comment]
yea that fixed it :)
